@startuml C2_Вариант1
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(директор, "Директор хозяйства", "Управление через веб-портал")
Person(аналитик, "Аналитик", "Работа с BI-системой")
Person(оператор_фермы, "Оператор фермы", "Локальный мониторинг и реакция")

System_Boundary(система, "Платформа мониторинга скота (MVP)") {

    Container_Boundary(агент_фермы, "Агент фермы") {
        ContainerDb(локальная_бд, "БД Фермы", "PostgreSQL + TimescaleDB", "Буферизация телеметрии, событий и метрик. Работа в оффлайн-режиме.")
        Container(iot_шлюз, "IOT шлюз", "Java", "Управление кормушками, поилками, датчиками. Сбор данных.")
        Container(агент_сбора_данных, "Агент сбора данных", "Java", "Сбор телеметрии, буферизация, базовые триггеры, передача видео.")
        Container(сервис_базовых_оповещений, "Сервис базовых оповещений", "Java", "Отправка уведомлений (email, SMS, мессенджеры).")
    }

    Container_Boundary(центральный_сервер, "Центральный сервер") {
        Container(сервис_оповещений, "Сервис оповещений", "Java", "Отправка уведомлений (email, SMS, мессенджеры).")
        Container(ml_сервер, "Сервер видеоаналитики", "ML модели предоставляются подрядчиком", "Обработка видеопотоков в реальном времени. Обнаружение ЧП (драки, задавливания, подсчёт).")
        Container(api_шлюз, "API Gateway", "Java", "Единая точка входа для API. Аутентификация, авторизация, маршрутизация.")
        Container(сервис_агрегации, "Сервис агрегации данных", "Java", "Прием и обработка данных от всех агентов. Синхронизация.")
        ContainerDb(центральная_бд, "Центральное хранилище", "PostgreSQL + TimescaleDB", "Исторические данные, метрики, события, конфигурации пользователей.")
        Container(сервис_аналитики, "Сервис аналитики и отчетности", "Java", "Прогнозирование расхода кормов, иных отчётов")
        Container(веб_портал, "Веб-портал", "Nginx, React", "Интерфейс для директора и аналитиков. Дашборды, управление фермами, пользователями.")
    }

    Container(мобильное_приложение, "Мобильное приложение", "Kotlin + Android Studio", "Для операторов. Просмотр статуса, получение push-уведомлений.")
}

System_Ext(bi_система, "BI система (Power BI)", "Корпоративная аналитика")
System_Ext(erp_система, "ERP система (1С:Агро)", "Финансы, склад, кадры")

System_Ext(камеры, "Видеокамеры(Wifi/Провод)", "Потоки для видеоаналитики")
System_Ext(кормушки, "Умные кормушки/поилки", "MQTT")
System_Ext(датчики, "Датчики (вода, еда)", "MQTT")

Rel(камеры, агент_сбора_данных, "Видеопотоки", "UDP/TCP")
Rel(датчики, iot_шлюз, "Передает данные", "MQTT")
Rel(iot_шлюз, кормушки, "Управляющие команды", "MQTT")

Rel(агент_сбора_данных, локальная_бд, "Сохраняет события и метрики", "SQL")
Rel(агент_сбора_данных, ml_сервер, "Видеопотоки", "UDP/TCP")
Rel(ml_сервер, сервис_оповещений, "Видеопотоки", "Kafka")
Rel(iot_шлюз, локальная_бд, "Сохраняет телеметрию", "SQL")
Rel(локальная_бд, сервис_агрегации, "Периодическая синхронизация\n(до 10 мин задержки)", "HTTPS/Rest API")
Rel(сервис_базовых_оповещений, оператор_фермы, "Базовые оповещения о ЧП (<5 сек)", "WebSocket/Push")
Rel(сервис_оповещений, оператор_фермы, "Расширенные оповещения о ЧП (<5 сек)", "WebSocket/Push")
Rel(сервис_оповещений, директор, "Важные оповещения (<5 сек)", "WebSocket/Push")
Rel(веб_портал, сервис_базовых_оповещений, "Управляет оповещениями")

Rel(api_шлюз, веб_портал, "Обслуживает запросы", "HTTPS")
Rel(api_шлюз, мобильное_приложение, "Обслуживает запросы", "HTTPS")
Rel(сервис_агрегации, центральная_бд, "Запись агрегированных данных", "SQL")
Rel(веб_портал, директор, "Использует для управления")
Rel(аналитик, bi_система, "Анализирует")
Rel(мобильное_приложение, оператор_фермы, "Использует")

Rel(сервис_аналитики, bi_система, "Экспорт данных для дашбордов", "ODBC/REST API")
Rel(api_шлюз, erp_система, "Синхронизация справочников (животные, корма)", "REST API")

Rel(агент_сбора_данных, сервис_базовых_оповещений, "Создает оповещение", "Kafka")
Rel(центральная_бд, сервис_аналитики, "Данные для анализа", "SQL")
Rel(веб_портал, сервис_аналитики, "Запрашивает отчеты", "gRPC")

@enduml